apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-service
  name: postgresql-service
spec:
  #endpoint of postgresql rds instance to connect 
  externalName: my-cluster.cijsdqmilarx.us-west-2.rds.amazonaws.com
  type: ExternalName
status:
  loadBalancer: {}